language: r
cache: packages

env:
  secure: eUoygpJjMQHbAp6TvJj8Dl/Hhh9NdFKF5uV2sm3iNVsn8r5Z5aGGmXf91ewDQKQ3z7nR85GmPR+OSCv7DrV+g6KT+YqeZkqWfYHKO0ZY/CdG56nINZTpJ5U2y2Q51yWN1T43PxTjwdaUQFMN78TBWU8oOXRbLSiyQQn/RMowOfu3SHot27f0whzenM3xzd7ugaC7tEFggSti/1B92jsEeIIXWUBXxTOwlz29AQaZ+v3ugDWOeE5Yes1N70Md8Qq9iFBJtqWk1FLh+u6fkLA3Rzn7co6M7RvjGkgW4QRxfey3qelITWnP25rPnfz99eYuBcLIvgfuGjU4jIgJ8rK0bevhnwCYSlzBKD6/8QeOnAl6L+1OMQahlF/8h58/BW7FiP6LwAA24xXgkAc2aA+B3Fu2uZGm+Nbpvd7QPocVbs89jLpG4/Oow8kgVUl8d6I5UjZ1Ni/vW+lhOELsFBEkIDBMXUkRc9ybmtwsIr8H+rRy2UDKmS47FHmzmCNpnR903uQ6vwAI9iU7KjoPx/1yCZ7zrVPaM6WOGOpFY+wBlZqtQRp47WirCGtP59ePErM0h12/krngCuoPdRK5rt0ZzDiAnzQfciGZHgBEWU7CC01NML5kAmwvwceP7uEqOLyOFVrhWFOflEeTjVFoKu8H9Pbfgki0MusA8IeTLsraJog=

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
